#!/bin/sh

running=$(ps aux | grep -- "-c dialog-kana" | grep -v grep)
if [ -z "${running}" ]; then
    $TERMINAL -c "dialog-kana" -e python3 ~/.local/repos/KanaKeyboard/keyboard.py -c &
    until xwininfo -tree -root | grep -q "dialog-kana"
    do
        sleep 0.1;
    done
fi
i3-msg '[class="dialog-kana"]' floating enable > /dev/null
i3-msg '[class="dialog-kana"]' border pixel 5 > /dev/null
i3-msg '[class="dialog-kana"]' resize set 600 100 > /dev/null
i3-msg '[class="dialog-kana"]' move position center > /dev/null
